/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arquivomunicipalpmpp.view;

import arquivomunicipalpmpp.cadastro.Cadastro;
import arquivomunicipalpmpp.cadastro.CadastroDAOHibernate;
import arquivomunicipalpmpp.util.Dados;
import arquivomunicipalpmpp.util.ModeloTabela;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Luís
 */
public class FrmArquivo extends javax.swing.JFrame
{

    Dados bd = new Dados();
    Cadastro cad = new Cadastro();
    CadastroDAOHibernate daoHibernate = new CadastroDAOHibernate();

    public FrmArquivo()
    {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        jComboBoxAno.requestFocus();
        mostraData();
        preencherTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButtonSalvar = new javax.swing.JButton();
        jButtonEscluir = new javax.swing.JButton();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldInfo = new javax.swing.JTextField();
        jComboBoxAno = new javax.swing.JComboBox();
        jComboBoxCaixa = new javax.swing.JComboBox();
        jComboBoxAssunto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDados = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonCaixa = new javax.swing.JRadioButton();
        jRadioButtonAssunto = new javax.swing.JRadioButton();
        jRadioButtonAno = new javax.swing.JRadioButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabelData = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema do Arquivo de Patrocínio Paulista");

        jButtonSalvar.setFont(new java.awt.Font("sansserif", 2, 16)); // NOI18N
        jButtonSalvar.setMnemonic('s');
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salva os dados preenchidos acima");
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEscluir.setFont(new java.awt.Font("sansserif", 2, 16)); // NOI18N
        jButtonEscluir.setMnemonic('E');
        jButtonEscluir.setText("Excluir");
        jButtonEscluir.setToolTipText("Exclui alguma dados, é preciso pesquisar o dados e importa-lo para o campo para poder excluí-lo");
        jButtonEscluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEscluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonEscluirActionPerformed(evt);
            }
        });

        jTextFieldCodigo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldCodigo.setEnabled(false);

        jTextFieldInfo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldInfo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTextFieldInfoKeyPressed(evt);
            }
        });

        jComboBoxAno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        jComboBoxCaixa.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxCaixa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200" }));

        jComboBoxAssunto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxAssunto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "ADITIVOS", "ATESTADOS E CERTIFICADOS DIVERSOS", "BAIXAS DE TRIBUTOS", "BALANÇOS DIVERSOS", "BOLETIM DIÁRIO TESOURARIA", "BOLSAS DE ESTUDO", "CARTA CONVITE", "CARTÕES DE PONTO", "CONCORRÊNCIA PÚBLICA", "CONCURSO PÚBLICO", "CONTABILIDADE", "CONTRATOS","CONTROLE DE COMBUSTÍVEIS", "CONVÊNIOS", "CORRESPONDÊNCIAS DIVERSAS", "CORRESPONDÊNCIAS EXPEDIDAS", "DECRETOS", "DESPACHO GP", "DÍVIDA ATIVA", "DÍVIDAS", "DOCUMENTOS DA EDUCAÇÃO", "DOCUMENTOS DIVERSOS", "DOCUMENTOS DO ALMOXARIFADO", "EDUCAÇÃO", "FOLHA DE PAGAMENTO", "FUNDEF", "GUIAS/TAXAS", "INDICAÇÕES RECEBIDAS CM", "IPVA", "ISENÇÃO DE IPTU", "LEIS", "LEIS/DECRETOS/PORTARIAS", "LICITAÇÕES", "MOVIMENTAÇÃO BANCÁRIA", "MOVIMENTOS DA CONTABILIDADE", "OFÍCIOS DIVERSOS", "OFÍCIOS EXPEDIDOS", "ORDEM DE FORNECIMENTO", "PATRIMÔNIO", "PLANTAS APROVADAS", "PORTARIAS", "PREGÃO ELETRÔNICO", "PREGÃO PRESENCIAL", "PRESTAÇÃO DE CONTAS", "PROC. DESP. EDUCAÇÃO", "PROCESSO SELETIVO", "PROCESSOS ADMINISTRATIVOS (RQ)", "PROCESSOS DE DESPESAS", "PROJETO P/ CELEBRAÇÃO DE CONVÊNIO", "PUBLICAÇÕES", "REC. ÁGUA, IPTU E DIVERSOS", "RECIBOS", "RELATÓRIOS", "REMISSIVO ALFABÉTICO", "RENDAS DIVERSAS", "REQ. RECEBIDOS CÂMARA MUNICIPAL", "REQUERIMENTO DIVERSOS", "REQUISIÇÃO DE CAÇAMBA", "RESTOS A PAGAR", "SAÚDE", "TOMADAS DE PREÇOS", "TRANSPORTE DE ALUNOS" }));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel1.setText("Id");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel2.setText("Ano");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel3.setText("Caixa");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel4.setText("Assunto");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setText("Informações");

        jTableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {},
                {},
                {},
                {}
            },
            new String []
            {

            }
        ));
        jTableDados.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTableDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDados);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        jRadioButtonCaixa.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadioButtonCaixa.setText("Nº Caixa");

        jRadioButtonAssunto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadioButtonAssunto.setSelected(true);
        jRadioButtonAssunto.setText("Assunto");

        jRadioButtonAno.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadioButtonAno.setText("Ano");

        jTextFieldPesquisar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldPesquisar.setToolTipText("Digite o que quer pesquisar");

        jButtonPesquisar.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jButtonPesquisar.setMnemonic('P');
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setToolTipText("Selecione o uma das opções para o filtro da pesquisa, digite no campo o que quer pesquisar e pressione o botão Pesquisar ou aperte a tecla Enter");
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jTextFieldPesquisar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonCaixa)
                            .addComponent(jRadioButtonAssunto)
                            .addComponent(jRadioButtonAno))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonAssunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCaixa)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonPesquisar, jTextFieldPesquisar});

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivomunicipalpmpp/imagens/Patrocinio_Paulista_-_brasao-57908.jpg"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Arquivo Municipal");

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Patrocínio Paulista");

        jLabel9.setText("Desenvolvido por:");

        jButton4.setText("Luís Henrique Nascimento");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("sansserif", 2, 16)); // NOI18N
        jButtonLimpar.setMnemonic('L');
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabelData.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabelData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelData.setText("Data:");
        jLabelData.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Backup");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldInfo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonEscluir, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jComboBoxCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jComboBoxAssunto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonLimpar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 93, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonEscluir, jButtonLimpar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonEscluir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelData)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonSalvar, jComboBoxAno, jComboBoxAssunto, jComboBoxCaixa, jTextFieldCodigo, jTextFieldInfo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonEscluir, jButtonLimpar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        FrmDesenvolvedor lh = new FrmDesenvolvedor();
        lh.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSalvarActionPerformed
    {//GEN-HEADEREND:event_jButtonSalvarActionPerformed
        if ((jTextFieldCodigo.getText().equals("")) || jTextFieldCodigo.getText().equals(""))
        {
            if ((jComboBoxAno.getSelectedItem().equals("")) || (jComboBoxAssunto.getSelectedItem().equals(""))
                    || (jComboBoxCaixa.getSelectedItem().equals("")) || (jTextFieldInfo.getText().equals("")))
            {
                JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
            } else
            {
                cad.setAno((String) jComboBoxAno.getSelectedItem());
                cad.setCaixa((String) jComboBoxCaixa.getSelectedItem());
                cad.setAssunto((String) jComboBoxAssunto.getSelectedItem());
                cad.setInfo(jTextFieldInfo.getText());

                daoHibernate.salvar(cad);
                JOptionPane.showMessageDialog(rootPane, "Cadastro inserido com sucesso!");
                preencherTabela();

                jTextFieldInfo.setText(null);
                jComboBoxAno.requestFocus();
            }

        } else
        {
            cad.setId(Integer.parseInt(jTextFieldCodigo.getText()));
            cad.setAno((String) jComboBoxAno.getSelectedItem());
            cad.setCaixa((String) jComboBoxCaixa.getSelectedItem());
            cad.setAssunto((String) jComboBoxAssunto.getSelectedItem());
            cad.setInfo(jTextFieldInfo.getText());

            daoHibernate.atualizar(cad);
            JOptionPane.showMessageDialog(rootPane, "Cadastro atualizado com sucesso!");
            preencherTabela();
            limparCampos();

        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLimparActionPerformed
    {//GEN-HEADEREND:event_jButtonLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonEscluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEscluirActionPerformed
    {//GEN-HEADEREND:event_jButtonEscluirActionPerformed
        cad.setId(Integer.parseInt(jTextFieldCodigo.getText()));

        daoHibernate.excluir(cad);
        JOptionPane.showMessageDialog(rootPane, "Cadastro excluído com sucesso!");
        preencherTabela();
        limparCampos();

    }//GEN-LAST:event_jButtonEscluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonPesquisarActionPerformed
    {//GEN-HEADEREND:event_jButtonPesquisarActionPerformed

//        ArrayList dados = new ArrayList();
//        String[] Colunas = new String[]
//        {
//            "Id", "Ano", "Caixa", "Assunto", "Informações"
//        };
//
//        cad.setAno(jTextFieldPesquisar.getText());
//        List<Cadastro> cadastro = daoHibernate.buscarPorAno(jTextFieldPesquisar.getText());
//
//        for (Cadastro c : cadastro)
//        {
//            dados.add(new Object[]
//            {
//                c.getId(),
//                c.getAno(),
//                c.getCaixa(),
//                c.getAssunto(),
//                c.getInfo()
//            });
//        }
//
//        ModeloTabela model = new ModeloTabela(dados, Colunas);
//        jTableDados.setModel(model);
//        jTableDados.getColumnModel().getColumn(0).setPreferredWidth(50);
//        jTableDados.getColumnModel().getColumn(0).setResizable(false);
//        jTableDados.getColumnModel().getColumn(1).setPreferredWidth(50);
//        jTableDados.getColumnModel().getColumn(1).setResizable(false);
//        jTableDados.getColumnModel().getColumn(2).setPreferredWidth(50);
//        jTableDados.getColumnModel().getColumn(2).setResizable(false);
//        jTableDados.getColumnModel().getColumn(3).setPreferredWidth(200);
//        jTableDados.getColumnModel().getColumn(3).setResizable(false);
//        jTableDados.getColumnModel().getColumn(4).setPreferredWidth(300);
//        jTableDados.getColumnModel().getColumn(4).setResizable(false);
//        jTableDados.getTableHeader().setReorderingAllowed(false);
//        jTableDados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//        jTableDados.isCellEditable(WIDTH, WIDTH);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed


    private void jTableDadosMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableDadosMouseClicked
    {//GEN-HEADEREND:event_jTableDadosMouseClicked
        if (evt.getClickCount() == 2)
        {
            String coluna0 = jTableDados.getValueAt(jTableDados.getSelectedRow(), 0).toString();
            jTextFieldCodigo.setText(coluna0);
            String coluna1 = jTableDados.getValueAt(jTableDados.getSelectedRow(), 1).toString();
            jComboBoxAno.setSelectedItem(coluna1);
            String coluna2 = jTableDados.getValueAt(jTableDados.getSelectedRow(), 2).toString();
            jComboBoxCaixa.setSelectedItem(coluna2);
            String coluna3 = jTableDados.getValueAt(jTableDados.getSelectedRow(), 3).toString();
            jComboBoxAssunto.setSelectedItem(coluna3);
            String coluna4 = jTableDados.getValueAt(jTableDados.getSelectedRow(), 4).toString();
            jTextFieldInfo.setText(coluna4);

            JOptionPane.showMessageDialog(rootPane, "Selecionado!");

        }
    }//GEN-LAST:event_jTableDadosMouseClicked

    private void jTextFieldInfoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldInfoKeyPressed
    {//GEN-HEADEREND:event_jTextFieldInfoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            if ((jTextFieldCodigo.getText().equals("")) || jTextFieldCodigo.getText().equals(""))
            {
                if ((jComboBoxAno.getSelectedItem().equals("")) || (jComboBoxAssunto.getSelectedItem().equals(""))
                        || (jComboBoxCaixa.getSelectedItem().equals("")) || (jTextFieldInfo.getText().equals("")))
                {
                    JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
                } else
                {
                    cad.setAno((String) jComboBoxAno.getSelectedItem());
                    cad.setCaixa((String) jComboBoxCaixa.getSelectedItem());
                    cad.setAssunto((String) jComboBoxAssunto.getSelectedItem());
                    cad.setInfo(jTextFieldInfo.getText());

                    daoHibernate.salvar(cad);
                    JOptionPane.showMessageDialog(rootPane, "Cadastro inserido com sucesso!");
                    preencherTabela();

                    jTextFieldInfo.setText(null);
                    jComboBoxAno.requestFocus();

                }

            } else
            {
                cad.setId(Integer.parseInt(jTextFieldCodigo.getText()));
                cad.setAno((String) jComboBoxAno.getSelectedItem());
                cad.setCaixa((String) jComboBoxCaixa.getSelectedItem());
                cad.setAssunto((String) jComboBoxAssunto.getSelectedItem());
                cad.setInfo(jTextFieldInfo.getText());

                daoHibernate.atualizar(cad);
                JOptionPane.showMessageDialog(rootPane, "Cadastro atualizado com sucesso!");
                limparCampos();
                preencherTabela();

                jTextFieldInfo.setText(null);
            }
        }
    }//GEN-LAST:event_jTextFieldInfoKeyPressed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu2MouseClicked
    {//GEN-HEADEREND:event_jMenu2MouseClicked
        FrmBackup bkp = new FrmBackup();
        bkp.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    public void limparCampos()
    {
        jTextFieldCodigo.setText(null);
        jComboBoxAno.setSelectedItem(null);
        jComboBoxAssunto.setSelectedItem(null);
        jComboBoxCaixa.setSelectedItem(null);
        jTextFieldInfo.setText(null);
    }

    public final void mostraData()
    {
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd 'de' MMMM 'de' yyyy");
        String data = sdf.format(new Date(System.currentTimeMillis()));
        jLabelData.setText(data);
    }

    public void preencherTabela()
    {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]
        {
            "Id", "Ano", "Caixa", "Assunto", "Informações"
        };

        cad.setAno(jTextFieldPesquisar.getText());
        List<Cadastro> cadastro = daoHibernate.listar();

        for (Cadastro c : cadastro)
        {
            dados.add(new Object[]
            {
                c.getId(),
                c.getAno(),
                c.getCaixa(),
                c.getAssunto(),
                c.getInfo()
            });
        }

        ModeloTabela model = new ModeloTabela(dados, Colunas);
        jTableDados.setModel(model);
        jTableDados.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableDados.getColumnModel().getColumn(0).setResizable(false);
        jTableDados.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableDados.getColumnModel().getColumn(1).setResizable(false);
        jTableDados.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTableDados.getColumnModel().getColumn(2).setResizable(false);
        jTableDados.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableDados.getColumnModel().getColumn(3).setResizable(false);
        jTableDados.getColumnModel().getColumn(4).setPreferredWidth(300);
        jTableDados.getColumnModel().getColumn(4).setResizable(false);
        jTableDados.getTableHeader().setReorderingAllowed(false);
        jTableDados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableDados.isCellEditable(WIDTH, WIDTH);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmArquivo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmArquivo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmArquivo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmArquivo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrmArquivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonEscluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxAno;
    private javax.swing.JComboBox jComboBoxAssunto;
    private javax.swing.JComboBox jComboBoxCaixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAno;
    private javax.swing.JRadioButton jRadioButtonAssunto;
    private javax.swing.JRadioButton jRadioButtonCaixa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTableDados;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldInfo;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
